[program:kashk-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /srv/kashk-al-ward/artisan queue:work redis --queue=notifications,default --sleep=3 --tries=3 --max-time=3600 --timeout=90
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/kashk-queue.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
stopwaitsecs=3600
